spring:
  datasource:
    url: jdbc:mysql://xxxx:3307/xxxx?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.com.toolWeb.model
  global-config:
    db-config:
      id-type: auto
app:
  swagger:
    base-package: cn.com.toolWeb
    title: codeBuilder
    description:

toolWeb:
  file:
    path: "d:\\tmp\\"